spring:
  application:
    name: HPassBook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  kafka:
    bootstrap-servers: 192.168.142.101:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  jpa:
    show-sql: true
    open-in-view: false
  redis:
    cluster:
      nodes:
      - 192.168.142.101:7001
      - 192.168.142.101:7002
      - 192.168.142.102:7003
      - 192.168.142.102:7004
      - 192.168.142.103:7005
      - 192.168.142.103:7006

hbase:
  zookeeper:
    quorum: 192.168.142.101,192.168.142.102,192.168.142.103
    property:
      clientPort: 2181
zookeeper:
  znode:
    parent: /hbase

server:
  port: 8082

logging:
  file: HPassbook.log
  level:
    root: warn
